# frozen_string_literal: true

require_relative "documentation"
require_relative "indexer"
require_relative "signature"

module RubyLsp
  module Yard
    # Maps (owner, name, singleton) to a {Signature} built from YARD tags (FR-M1-10). Fills lazily and memoizes
    # (NFR-P5), follows `(see ...)` references and inheritance, interprets the M1 directives, and drops its caches
    # when watched files change (FR-M1-11). Never raises: failures degrade to `nil` (NFR-R1).
    class SignatureStore
      MISS = Object.new
      REFERENCE = /\A(?:(?<owner>[A-Za-z_][\w:]*))?(?<separator>[#.])(?<method>[^#.]+)\z/

      def initialize(adapter, log: nil, rbs: nil, gem_cache: nil, macros: nil, inline: nil)
        @adapter = adapter
        @log = log
        @rbs = rbs
        @gem_cache = gem_cache
        @macros = macros
        @inline = inline
        @extractor = Documentation::TagExtractor.new(log: log)
        @builder = Documentation::SignatureBuilder.new(adapter, log: log)
        @cache = {}
        @directive_cache = {}
        @visibility_overrides = {}
        @mutex = Mutex.new

        adapter.subscribe { |uris| invalidate(uris) }
        # Core signatures looked up while the RBS environment was still loading were pinned to their YARD/host
        # fallback; drop the caches once RBS can answer (FR-M3-04).
        @rbs&.subscribe { invalidate(nil) }
      end

      def lookup(owner, name, singleton: false)
        return nil if owner.nil? || name.nil?

        key = [owner.to_s, name.to_s, singleton]
        cached = @mutex.synchronize { @cache.fetch(key, MISS) }
        return cached unless cached.equal?(MISS)

        signature = build(key[0], key[1], singleton, visited: [])
        @mutex.synchronize { @cache[key] = signature || MISS }
        signature
      rescue => e
        @log&.error("Signature lookup failed for #{owner}##{name}: #{e.class}: #{e.message}")
        nil
      end

      # A watched file changed. Entries are rebuilt lazily on the next lookup; clearing everything is a superset of
      # invalidating just the changed files and keeps the caches consistent.
      def invalidate(_uris)
        @mutex.synchronize do
          @cache.clear
          @directive_cache.clear
          @visibility_overrides.clear
        end
      end

      private

      def build(owner, name, singleton, visited:)
        key = [owner, name, singleton]
        return nil if visited.include?(key)

        visited += [key]

        # FR-M3-04 (D5): where RBS and YARD both describe a method, RBS wins.
        rbs_signature = rbs_lookup(owner, name, singleton)
        return rbs_signature if rbs_signature

        # Populates visibility overrides stored on the owner's own definitions.
        directives = directive_entries(owner)
        fallback = nil

        @adapter.method_definitions(owner, name, singleton: singleton).each do |definition|
          signature = signature_from_definition(definition, name, singleton, visited)
          next unless signature
          return signature if signature.documented?

          fallback ||= signature
        end

        directive = directives[[name, singleton]]
        return directive if directive

        # FR-M7-01: definitions generated by an attached macro's expansion at a DSL call site.
        macro = @macros&.lookup(owner, name, singleton: singleton)
        return macro if macro

        receiver = receiver_owner(owner, singleton)
        ancestors = @adapter.ancestors(receiver)

        ancestors.each do |ancestor|
          next if ancestor == receiver

          # Ancestors contribute their instance methods to both kinds of receivers (`extend` mixes a module's
          # instance methods into the singleton), so the singleton flag is not passed on.
          inherited_rbs = rbs_lookup(ancestor, name, false)
          return inherited_rbs if inherited_rbs

          @adapter.method_definitions(ancestor, name).each do |definition|
            signature = signature_from_definition(definition, name, singleton, visited)
            next unless signature
            return signature if signature.documented?

            fallback ||= signature
          end
        end

        # Directives attached to a superclass comment or method; macro-generated methods on ancestors are inherited
        # too (FR-M7-01).
        ancestors.each do |ancestor|
          ancestor_owner = base_owner(ancestor)
          next if ancestor_owner == owner

          signature = directive_entries(ancestor_owner)[[name, singleton]]
          return signature if signature

          inherited_macro = @macros&.lookup(ancestor_owner, name, singleton: singleton)
          return inherited_macro if inherited_macro
        end

        fallback
      end

      def signature_from_definition(definition, name, singleton, visited)
        # FR-M7-04: `rbs-inline` annotations in the file outrank its YARD comments (D5).
        inline = inline_lookup(definition, name, singleton)
        return inline if inline

        gem = gem_identity(definition)
        cache_key = gem_cache_key(definition, singleton)

        if gem && cache_key
          cached = @gem_cache&.read(gem, cache_key)
          return cached if cached
        end

        raw = @extractor.extract(expand_comments(definition.comments, definition.name))

        if raw.reference
          resolved = resolve_reference(raw.reference, definition, visited)
          return resolved if resolved
        end

        signature = @builder.build(
          definition,
          raw,
          name: name,
          singleton: singleton,
          visibility: visibility_for(definition, singleton)
        )
        @gem_cache&.write(gem, cache_key, signature) if gem && cache_key && signature&.documented?
        signature
      rescue => e
        @log&.error("Failed to build signature for #{definition.name}: #{e.class}: #{e.message}")
        nil
      end

      # FR-M3-05: gem docstrings are parsed lazily and the built signatures persist to the disk cache.
      def gem_identity(definition)
        return nil unless @gem_cache

        @gem_cache.identity(definition.uri || definition.file_name)
      rescue
        nil
      end

      def gem_cache_key(definition, singleton)
        return nil unless definition.owner && definition.name

        [definition.owner, definition.name, singleton_for(definition) || singleton]
      end

      # FR-M3-04: RBS answers for core and stdlib owners (and their ancestors) before YARD.
      def rbs_lookup(owner, name, singleton)
        @rbs&.lookup(owner, name, singleton: singleton)
      rescue => e
        @log&.error("RBS signature lookup failed for #{owner}##{name}: #{e.class}: #{e.message}")
        nil
      end

      # FR-M7-04: `rbs-inline` annotations in the definition's own file.
      def inline_lookup(definition, name, singleton)
        return nil unless @inline

        owner = @builder.base_owner(definition.owner.to_s)
        return nil if owner.empty?

        @inline.lookup(definition.uri, owner, name, singleton: singleton_for(definition) || singleton)
      rescue => e
        @log&.error("rbs-inline lookup failed for #{name}: #{e.class}: #{e.message}")
        nil
      end

      # --- Directives (FR-M1-03) ---------------------------------------------------------------------------------

      def directive_entries(owner)
        @mutex.synchronize { return @directive_cache[owner] if @directive_cache.key?(owner) }

        entries = build_directive_entries(owner)
        @mutex.synchronize { @directive_cache[owner] = entries }
        entries
      end

      def build_directive_entries(owner)
        entries = {}
        own_owners = [owner, receiver_owner(owner, true)]

        definitions = []
        definitions.concat(@adapter.methods_of(owner))
        definitions.concat(@adapter.methods_of(owner, singleton: true))
        definitions.concat(@adapter.constant_definitions(owner))

        definitions.each do |definition|
          next unless definition.owner.nil? || own_owners.include?(definition.owner)

          # Named macro invocations can inject directives, so expansion happens before the `@!` check (FR-M7-01).
          comments = expand_comments(definition.comments.to_s, definition.name)
          next unless comments.include?("@!")

          raw = @extractor.extract(comments)
          visibility = @builder.extract_visibility(raw)
          apply_visibility_override(definition, visibility) if visibility

          @builder.apply_directives(
            entries,
            owner: owner,
            raw: raw,
            visibility: visibility,
            uri: definition.uri,
            location: definition.location
          )
        end

        entries
      end

      # --- Helpers -----------------------------------------------------------------------------------------------

      def resolve_reference(reference, definition, visited)
        match = REFERENCE.match(reference.to_s)
        return nil unless match

        owner = if match[:owner]
          @adapter.resolve_constant(match[:owner], nesting_for(definition.owner.to_s))
        else
          base_owner(definition.owner.to_s)
        end
        return nil if owner.nil? || owner.empty?

        singleton = match[:separator] == "."
        key = [owner, match[:method], singleton]
        return nil if visited.include?(key)

        build(owner, match[:method], singleton, visited: visited)
      end

      def visibility_for(definition, singleton)
        # `@!visibility` overrides are collected while scanning an owner's directives. A definition may belong to
        # an ancestor (inherited method), so make sure that owner has been scanned before reading the override.
        directive_entries(base_owner(definition.owner)) if definition.owner
        @visibility_overrides[[definition.owner, definition.name, singleton_for(definition) || singleton]]
      end

      def apply_visibility_override(definition, visibility)
        return if definition.owner.nil?

        @visibility_overrides[[definition.owner, definition.name, singleton_for(definition)]] = visibility
      end

      # FR-M7-01: named macro invocations are expanded before the comment is parsed as YARD.
      def expand_comments(comments, method_name)
        @macros ? @macros.expand_comments(comments, method_name: method_name) : comments
      end

      # Constant lookup nesting for an owner: `FixtureProject::Animal` -> `["FixtureProject", "Animal"]`.
      def nesting_for(owner)
        base_owner(owner).split("::").reject(&:empty?)
      end

      def base_owner(name)
        name.to_s.sub(/::<Class:[^>]+>\z/, "")
      end

      def receiver_owner(owner, singleton)
        return owner.to_s unless singleton

        unqualified = owner.to_s.split("::").last
        "#{owner}::<Class:#{unqualified}>"
      end

      def singleton_for(definition)
        definition.owner.to_s.include?("::<Class:")
      end
    end
  end
end
